[package]
name = "pinetime-rust"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[build-dependencies]
chrono = "0.4.24"

[dependencies]
# Core dependencies
cortex-m = { version = "0.7", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7"
cortex-m-rtic = "1.1"
embedded-hal = "0.2"
# Enable `rt` feature but disable xxAB-package
nrf52832-hal = { version = "0.16", features = ["rt"], default-features = false }

# IO
debouncr = "0.2"

# Bluetooth
# nrf-softdevice = "0.0.0"
rubble = { git = "https://github.com/thecodechemist99/rubble", dir = "tree/master/rubble"}
rubble-nrf5x = { git = "https://github.com/thecodechemist99/rubble", dir = "tree/master/rubble-nrf5x", features = ["52832"] }

# Graphics
chrono = { version = "0.4", default-features = false }
display-interface-spi = "0.4"
embedded-graphics = "0.7"
format_no_std = "1.0"
fugit = "0.3"
mipidsi = "0.6"
profont = "0.6"

# Debug probe
defmt = "0.3"
defmt-rtt = "0.4"
panic-probe = { version = "0.3", features = ["print-defmt"] }

[profile.dev]
# opt-level = "z"
# strip = false

[profile.release]
opt-level = "z"
codegen-units = 1
lto = true
strip = true
panic = 'abort'
