[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# replace nRF52832_xxAA with your chip as listed in `probe-run --list-chips`
runner = "probe-run --chip nRF52832_xxAA"

rustflags = [
    "-C", "link-arg=--nmagic",
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv7em-none-eabihf"

[env]
DEFMT_LOG = "trace"